services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./main.py"
    volumes:
      - ./python:/usr/app/src

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
  

volumes:
  index_data:
    driver: local