services:
  pythonapp:
    container_name: vecragbot
    build: ./python/  
    stdin_open: true # Keeps the container open to receive user input
    tty: true # Allocates a pseudo-terminal for the container
    volumes:
      - ./python:/usr/app/src

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

volumes:
  index_data:
    driver: local